# Generated by Django 2.2.2 on 2019-06-09 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('gender', models.BooleanField(default=True)),
                ('qq', models.CharField(max_length=12)),
                ('weixin', models.CharField(max_length=20)),
                ('licence_number', models.CharField(max_length=20)),
                ('has_seat', models.BooleanField(default=False)),
                ('seat_number', models.CharField(max_length=40)),
                ('id_number', models.CharField(max_length=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
