# Generated by Django 2.2.2 on 2019-06-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_userprakseat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprakseat',
            name='stat02',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat1012',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat1214',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat1416',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat1618',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat1820',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat2022',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat2224',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat24',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat46',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat68',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprakseat',
            name='stat810',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
