# Generated by Django 2.2.2 on 2019-06-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_auto_20190625_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_source', to='park.UserPrakSeat'),
        ),
    ]
