# Generated by Django 2.2.2 on 2019-06-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0005_auto_20190626_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('status', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_seat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='seat_number',
        ),
        migrations.CreateModel(
            name='Lock_Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carlock', to='park.CarLock')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.UserPrakSeat')),
            ],
        ),
    ]
