# Generated by Django 2.2.2 on 2019-06-27 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_auto_20190626_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprakseat',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
