# Generated by Django 2.2.2 on 2019-06-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_auto_20190627_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='qq',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weixin',
        ),
    ]
